import type { Metadata } from "next";
import '@/styles/globals.scss';
import { Providers } from '@/_helper/provider';
import { fonts } from '@/_helper/font';
import { ColorModeScript } from "@chakra-ui/react";
import { theme } from '@/styles/theme'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en' className={fonts.rubik.variable}>
      <body>
        <Providers>
          {/* <ColorModeScript initialColorMode='dark' /> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
